### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [jakee246/project2#1]
It looks like you're not quite serving valid HTML here. See if you can fix [the errors](http://validator.w3.org/check?uri=https%3A%2F%2Ftc359project2.herokuapp.com%2F&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices).

**Comment by chrisvfritz** [comment]
:+1: Problem fixed in the next project.

**Comment by jakee246** [comment]
http://validator.w3.org/check?uri=https%3A%2F%2Ftc359project2.herokuapp.com&charset=%28detect+automatically%29&doctype=Inline&group=0

Problem corrected in Project 2 as well.

Thank you.

**Comment by chrisvfritz** [comment]
Very nice! Looks good.
